LOGGER:
  PATH: /home/moler/gitrepos/moler/trainings/workshop1/logs  # yours might differ
  RAW_LOG: True
  DEBUG_LEVEL: DEBUG
  DATE_FORMAT: "%Y-%m-%d %H:%M:%S"

DEVICES:
  MyMachine1:
    DEVICE_CLASS: moler.device.unixlocal.UnixLocal

  MyMachine2:
    DEVICE_CLASS: moler.device.unixlocal.UnixLocal
