language: python
python:
  - 2.7
  - 3.6
install:
  - pip install -U pip
  - pip install -U coveralls
before_script:
  - pip install -Ur requirements.txt
  - python2 -V
  - python3 -V
script:
  - coverage run --source=moler,test -m py.test -vv
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 && $TRAVIS_OS_NAME != "linux" ]]; then coveralls; fi
