language: python
python:
  - 2.7
  - 3.6
install:
  # - pip install -r requirements.txt
  - pip2 list
  - pip3.6 list
before_script:
  - python2 -V
  - python3 -V
script:
  - uptime
after_success:
  - env
