language: python
matrix:
  include:
    - python: 2.7
      env: ASYNC=
    - python: 3.6
      env: ASYNC=pytest-asyncio
    - python: 3.7
      env: ASYNC=pytest-asyncio
    - python: 3.8
      env: ASYNC=pytest-asyncio

install:
  - pip install -U pip
  - pip install -U pycodestyle coveralls pytest pytest-mccabe pytest-random $ASYNC
  - pip install -Ur requirements.txt

before_script:
  - python2 -V
  - python3 -V

script:
  - python -m pycodestyle moler
  - python -m pytest test
  - python -m pytest --mccabe moler
  - coverage run -m pytest -c py3pytest.ini --random

after_success:
  - coveralls

after_failure:
  - echo "----------------------- LOGS -----------------------"
  - cat *.log

#stages:
#- style
#- test
#
#jobs:
#  include:
#  - stage: style
#    language: python
#    python: 2.7
#    install:
#    - pip install -U pip
#    - pip install -U pycodestyle
#    before_script:
#    - pip install -Ur requirements.txt
#    - python2 -V
#    env:
#    - NAME="Style"
#    script:
#    - pycodestyle moler
#  - stage: style
#    language: python
#    python: 3.7
#    install:
#    - pip install -U pip
#    - pip install -U pycodestyle
#    before_script:
#    - pip install -Ur requirements.txt
#    - python3 -V
#    env:
#    - NAME="Style"
#    script:
#    - pycodestyle moler
#  - stage: test
#    language: python
#    python: 2.7
#    install:
#    - pip install -U pip
#    - pip install -U pytest pytest-mccabe pytest-random
#    before_script:
#    - pip install -Ur requirements.txt
#    - python2 -V
#    env:
#    - NAME="Test"
#    script:
#    - python2.7 -m pytest --random -s -vv test
#    after_failure:
#    - ls -laR
#    - cat *.log
#  - stage: test
#    language: python
#    python: 3.7
#    install:
#    - pip install -U pip
#    - pip install -U coveralls pytest pytest-mccabe pytest-random pytest-asyncio
#    before_script:
#    - pip install -Ur requirements.txt
#    - python3 -V
#    env:
#    - NAME="Test"
#    script:
#    - python3.7 -m pytest --mccabe moler
#    - coverage run -m pytest -c py3pytest.ini --random  -s -vv
#    after_success:
#    - coveralls
#    after_failure:
#    - ls -laR
#    - cat *.log
