language: python
dist: bionic
matrix:
  include:
    - python: 2.7.17
      env: ASYNC=
    - python: 3.6.10
      env: ASYNC=pytest-asyncio
    - python: 3.7.4
      env: ASYNC=pytest-asyncio
    - python: 3.8.1
      env: ASYNC=pytest-asyncio

install:
  - pip install -U pip
  - pip install -U pycodestyle coveralls pytest pytest-mccabe pytest-random $ASYNC
  - pip install -Ur requirements.txt

before_script:
  - python -V

script:
  - python -m pycodestyle --statistics --count moler
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7.17 ]]; then python -m pytest --random test; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6.10 ]]; then python -m pytest -c py3pytest.ini --random --mccabe; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7.4 ]]; then coverage run -m pytest -c py3pytest.ini --random --mccabe; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.8.1 ]]; then python -m pytest --mccabe moler; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7.4 ]]; then coveralls; fi

after_failure:
  - echo "----------------------- LOGS -----------------------"
  - ls -lah *.log
  - cat *.log

#stages:
#- style
#- test
#
#jobs:
#  include:
#  - stage: style
#    language: python
#    python: 2.7
#    install:
#    - pip install -U pip
#    - pip install -U pycodestyle
#    before_script:
#    - pip install -Ur requirements.txt
#    - python2 -V
#    env:
#    - NAME="Style"
#    script:
#    - pycodestyle moler
#  - stage: style
#    language: python
#    python: 3.7
#    install:
#    - pip install -U pip
#    - pip install -U pycodestyle
#    before_script:
#    - pip install -Ur requirements.txt
#    - python3 -V
#    env:
#    - NAME="Style"
#    script:
#    - pycodestyle moler
#  - stage: test
#    language: python
#    python: 2.7
#    install:
#    - pip install -U pip
#    - pip install -U pytest pytest-mccabe pytest-random
#    before_script:
#    - pip install -Ur requirements.txt
#    - python2 -V
#    env:
#    - NAME="Test"
#    script:
#    - python2.7 -m pytest --random -s -vv test
#    after_failure:
#    - ls -laR
#    - cat *.log
#  - stage: test
#    language: python
#    python: 3.7
#    install:
#    - pip install -U pip
#    - pip install -U coveralls pytest pytest-mccabe pytest-random pytest-asyncio
#    before_script:
#    - pip install -Ur requirements.txt
#    - python3 -V
#    env:
#    - NAME="Test"
#    script:
#    - python3.7 -m pytest --mccabe moler
#    - coverage run -m pytest -c py3pytest.ini --random  -s -vv
#    after_success:
#    - coveralls
#    after_failure:
#    - ls -laR
#    - cat *.log
