language: python
dist: bionic
matrix:
  include:
    - python: 2.7.17
    - python: 3.6.10
    - python: 3.7.3
    - python: 3.8.1

install:
  - pip install -U pip
  - pip install -U pycodestyle coveralls pytest pytest-mccabe pytest-random
  - if [[ $TRAVIS_PYTHON_VERSION == *"3."* ]]; then pip install -U pytest-asyncio; fi
  - pip install -Ur requirements.txt

before_script:
  - python -V
  - cat /etc/passwd | grep home

script:
  - python -m pycodestyle --statistics --count moler
  - if [[ $TRAVIS_PYTHON_VERSION == *"2.7"* ]]; then python -m pytest --random -s -vv test; fi
  - if [[ $TRAVIS_PYTHON_VERSION == *"3.6"* ]]; then python -m pytest -c py3pytest.ini --random --mccabe -s -vv; fi
  - if [[ $TRAVIS_PYTHON_VERSION == *"3.7"* ]]; then coverage run -m pytest -c py3pytest.ini --random --mccabe -s -vv; fi
  - if [[ $TRAVIS_PYTHON_VERSION == *"3.8"* ]]; then python -m pytest --mccabe -s -vv moler; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == *"3.7"* ]]; then coveralls; fi

after_failure:
  - echo "----------------------- LOGS -----------------------"
  - ls -lah *.log
  - cat *.log
